### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by midna666** [clear-code-projects/PyDew-Valley#5]
Hey,

thank you for this amazing guide , i am following you to learn Pygame

i tried your code and faced the below issue can you please help here ? I see someone else had trouble with this but the issue was closed with no solution for us other coders to see.

Traceback (most recent call last):
File "d:\Pygame\Survival\code\main.py", line 25, in
game = Game()
File "d:\Pygame\Survival\code\main.py", line 11, in init
self.level = Level()
File "d:\Pygame\Survival\code\level.py", line 14, in init
self.setup()
File "d:\Pygame\Survival\code\level.py", line 17, in setup
self.player = Player((640,360), self.all_sprites)
File "d:\Pygame\Survival\code\player.py", line 14, in init
self.image = self.animations[self.status][self.frame_index]
IndexError: list index out of range

i didnt change anything , just run your code

**Comment by Arfaller0523** [comment]
I get the same problem and can't figure out where the problem is

**Comment by Pin-ball** [comment]
Hi, the asset pack has changed since this code/tutorial has been done. Now Characters animations are not in separate folders anymore, so import_assets() function doesn't collect any image and self.animations dictionary contains no images just empty arrays.

**Comment by Arfaller0523** [comment]
> Hi, the asset pack has changed since this code/tutorial has been done. Now Characters animations are not in separate folders anymore, so import_assets() function doesn't collect any image and self.animations dictionary contains no images just empty arrays.

Thanks alot, hope you have a good day!

**Comment by spyridonpallis** [comment]
@Pin-ball This is incorrect.

@Arfaller0523 @midna666 The code runs fine. Please make sure to cd into the 'code' directory before you run main.py

**Comment by Shayalt** [comment]
I have done everything just as I was supposed to and checked for errors. I also have the individual files for the images, as in the video. I do not understand why I am still getting the index out of range error. Just before adding the support file code, everything was working fine. I also noticed that my support code function for import folder does not print out anything. I can't see any of the output shown in the video for that method. Please help.

**Comment by tiarakabra** [comment]
@spyridonpallis when i run my code it shows a black output screen hows ur code running fine?
